version: '3.1'

services: 

# Database server
# boondocks-db:
#   image: microsoft/mssql-server-linux
#   environment: 
#     - ACCEPT_EULA=Y
#     - SA_PASSWORD=987ysnskaFsf 
#   ports:
#     -  1500:1433 
#     -  1501:1434 

  boondocks-auth-api:
    build:
      context: .
      dockerfile: Boondocks-Auth.Dockerfile
    image: boondocks-auth-api
    volumes: 
      - ./content/certs:/certs
    environment:
      - boondocks__auth__jwt__certificateFilePath=/certs/auth-private.pfx
      - boondocks__auth__jwt__issuer="boondocks-auth-api" 
      - boondocks__auth__jwt__audience="boondocks-registry"
      - boondocks__auth__jwt__validForMinutes=10080
      - boondocks__auth__ldap__DomainName="CAPTIVE_AIRE"
      - boondocks__auth__ldap__Connection=2008dc1.captiveaire.com
      - boondocks__auth__ldap__Port=389
    ports:
      - 8080:80

  boondocks-device-api:
    build:
      context: .
      dockerfile: Boondocks-Device.Dockerfile
    image: boondocks-device-api
    environment:
      - boondocks__registry__host="http://registry.captiveaire.com"
      - boondocks__connections__device__connectionString=Server=devdb.captiveaire.com;Database=Boondocks;User Id=boondocks;Password=ak*7sjfgum;
    ports:
      - 8081:80


  # # management web site

  # # Docker Registry
  # boondocks-registry:
  #   image: registry:2
  #   environment:
  #     - REGISTRY_LOG_LEVEL=debug
  #     - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
  #     - REGISTRY_AUTH=token
  #     - REGISTRY_AUTH_TOKEN_REALM=http://desktop-richq.captiveaire.com/AuthTest/token
  #     - REGISTRY_AUTH_SERVICE="Docker registry"
  #     - REGISTRY_AUTH_ISSUER="issuer"
  #     - REGISTRY_AUTH_ROOTCERTBUNDLE=/ssl/registry-auth-cert.pem
  #   volumes:
  #     - auth_certs:/ssl
  #     - /root/docker_registry/data:/var/lib/registry
  #   ports:
  #     - 5000:5000

volumes:
  auth_certs:

networks:
  default:
    
